<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/12/12 19:32:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=nefeli',
  'username' => 'nefeli',
  'password' => 'nefeli',
  'name' => 'doctrine',
)),);
